# Generated by Django 2.0.2 on 2018-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
