# Generated by Django 2.0.2 on 2018-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_vaultwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultwallet',
            name='user',
        ),
        migrations.AddField(
            model_name='vaultwallet',
            name='username',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
