# Generated by Django 2.0.2 on 2018-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0011_vaultretrieverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultretrieverequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
