# Generated by Django 2.0.2 on 2018-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_auto_20180312_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultretrieverequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
