# Generated by Django 2.0.2 on 2018-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_moneropaymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneropaymentid',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
