# Generated by Django 2.0.2 on 2018-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_status',
            field=models.BooleanField(default=False),
        ),
    ]
