# Generated by Django 2.0.2 on 2018-02-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180206_0610'),
        ('authentication', '0002_user_two_factor_status'),
    ]

    operations = [
    ]
