# Generated by Django 2.0.2 on 2018-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20180206_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(help_text='City of Permanent Residence', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(help_text='Country of Permanent Residence', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default=1, help_text='pincode/zipcode of your area', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(help_text='State of Permanent Residence', max_length=128),
        ),
    ]
