# Generated by Django 2.0.2 on 2018-02-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180206_1253'),
        ('authentication', '0005_auto_20180206_1219'),
    ]

    operations = [
    ]
