# Generated by Django 2.0.2 on 2018-02-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20180207_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_status',
            field=models.BooleanField(),
        ),
    ]
