# Generated by Django 2.0.2 on 2018-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20180209_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pincode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(default=1, help_text='Zipcode', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(help_text='Home Address', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(help_text='Apartment/Suite number', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(help_text='City', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(help_text='Country', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(help_text='State', max_length=128),
        ),
    ]
