# Generated by Django 2.0.2 on 2018-02-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20180228_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
