# Generated by Django 2.0.2 on 2018-03-16 10:56

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20180315_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True),
        ),
    ]
