# Generated by Django 2.0.2 on 2018-03-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='landmark',
        ),
    ]
