# Generated by Django 2.0.2 on 2018-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='passphrase',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
